# -*- coding: utf-8 -*-
"""Dicionario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WUMB79Yc3vknBKacGbrAtUunQ9hP7tJQ

Crie um dicionário que é uma agenda e coloque nele os seguintes dados: chave (cpf),
nome, idade, telefone. O programa deve ler um número indeterminado de dados, criar a
agenda e imprimir todos os itens do dicionário no formato chave: nome, idade, fone.
"""

def main():
    agenda = {}


    while True:
        cpf = input("Digite o CPF: ")
        nome = input("Digite o nome: ")
        idade = input("Digite a idade: ")
        telefone = input("Digite o telefone: ")

        agenda[cpf] = {
            "nome": nome,
            "idade": idade,
            "telefone": telefone,
        }

        continuar = input("Deseja continuar? (s/n): ")
        if continuar != "s":
            break

    for cpf, contato in agenda.items():
        print(cpf, contato["nome"], contato["idade"], contato["telefone"])


if __name__ == "__main__":
    main()

"""Construa um dicionário com nome, salariobruto, salario liquido,
para número indeterminado de pessoas, nele será calculado o
desconto de 8% do INSS e de 10% para IRPF. Preciso que o
programa seja escrito na Linguagem Python de forma Otimizada..
"""

def main():
    folha_de_pagamento = {}

    while True:
        nome = input("Digite o nome: ")
        salario_bruto = float(input("Digite o salário bruto: "))

        desconto_inss = salario_bruto * 0.08

        desconto_irpf = 0
        if salario_bruto > 1903.98:
            desconto_irpf = salario_bruto * 0.10

        salario_liquido = salario_bruto - desconto_inss - desconto_irpf

        folha_de_pagamento[nome] = {
            "salario_bruto": salario_bruto,
            "desconto_inss": desconto_inss,
            "desconto_irpf": desconto_irpf,
            "salario_liquido": salario_liquido,
        }

        continuar = input("Deseja continuar? (s/n): ")
        if continuar != "s":
            break

    for nome, dados in folha_de_pagamento.items():
        print(nome, dados["salario_bruto"], dados["desconto_inss"], dados["desconto_irpf"], dados["salario_liquido"])


if __name__ == "__main__":
    main()

