# -*- coding: utf-8 -*-
"""Vetores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJSisilWDOFZtARqSQWGp44wyOLsiKPn
"""

def main():
  valor = True
  vetor = [0] * 8
  for i in range(8):
    vetor[i] = int(input("Digite o número da posição {}: ".format(i+1)))

  while(valor):
    x = int(input("Digite o valor de X : "))
    y = int(input("Digite o valor de Y : "))
    if(x < 8 and x > 0 and y < 8 and y > 0 ):
      valor = False
    if (not(x < 8 and x > 0 and y < 8 and y > 0)):
      print("Alguma posição Inválida")
  soma = vetor[x-1] + vetor[y-1]
  print("A soma dos valores nas posições X e Y é: {}".format(soma))
main()

def main():
  valor = True
  menor = 0
  maior = 0
  maior_cinco = 0
  vetor = [0] * 10
  soma = 0
  for i in range(10):
    vetor[i] = int(input("Digite o número da posição {}: ".format(i+1)))
    if(i == 0):
      menor = vetor[i]
    if(vetor[i] > maior):
      maior = vetor[i]
    if (vetor[i] < menor):
      menor = vetor[i]
    if(vetor[i] > 5):
      maior_cinco+=1
  for i in range(10):
    soma += vetor[i]

  print("A soma é: {}".format(soma))
  print("A média é: {}".format(soma/10))
  print("Números maiores que 5: {}".format(maior_cinco))
  print("Maior valor: {}".format(maior))
  print("Menor valor: {}".format(menor))
main()

"""Faça um programa em Python que receba do usuario
um vetor com 10 posições. Em seguida devera ser
impresso o maior e o menor elemento do vetor.
"""

def main():
    vetor = []
    for i in range(10):
        vetor.append(int(input("Digite o elemento %d: " % i)))
    maior = vetor[0]
    menor = vetor[0]
    for i in range(1, len(vetor)):
        if vetor[i] > maior:
            maior = vetor[i]
        elif vetor[i] < menor:
            menor = vetor[i]
    print("O maior elemento do vetor é %d." % maior)
    print("O menor elemento do vetor é %d." % menor)

if __name__ == "__main__":
    main()

"""Programa que receba 6 numeros inteiros e mostre: Os numeros pares digitados;
- A soma dos numeros pares digitados;
- Os numeros   ımpares digitados;
- 3A quantidade de numeros  ımpares
"""

def main():
    numeros = []
    numeros_pares = []
    numeros_impares = []
    soma_pares = 0

    for i in range(6):
        numeros.append(int(input("Digite um número: ")))

    for numero in numeros:
        if numero % 2 == 0:
            numeros_pares.append(numero)
            soma_pares += numero
        else:
            numeros_impares.append(numero)

    print("Os números pares digitados são:")
    for numero in numeros_pares:
        print(numero)

    print("A soma dos números pares digitados é:", soma_pares)

    print("Os números ímpares digitados são:")
    for numero in numeros_impares:
        print(numero)

    print("A quantidade de números ímpares digitados é:", len(numeros_impares))


if __name__ == "__main__":
    main()

def main():
    vetor_a = []
    vetor_b = []
    vetor_c = []

    for i in range(10):
        vetor_a.append(int(input("Digite o elemento %d do vetor A: " % i)))
        vetor_b.append(int(input("Digite o elemento %d do vetor B: " % i)))

    for i in range(10):
        vetor_c.append(vetor_a[i] - vetor_b[i])

    print("Vetor C:")
    for i in range(10):
        print(vetor_c[i])


if __name__ == "__main__":
    main()

